apiVersion: v1
kind: ConfigMap
metadata:
  name: vcl-template
data:
  default.vcl: |
    vcl 4.0;

    acl purge {
      "172.17.0.0/16";
    }
    
    backend default {
      .host = "172.17.42.1";
      .port = "8080";
    }
    
    sub vcl_recv {
      if (!(req.url ~ "cached")) {
        unset req.http.cookie;
      }
      if (req.url == "/") {
        return (pass);
      }
    
      if (req.method == "PURGE") {
        if (!client.ip ~ purge) {
          return(synth(405,"Not allowed."));
        }
        return (purge);
      }
    }
    
    sub vcl_backend_response {
      if (!(bereq.url ~ "cached")) {
        unset beresp.http.set-cookie;
      }
    }
    
    sub vcl_deliver {
      # Happens when we have all the pieces we need, and are about to send the
      # response to the client.
      #
      # You can do accounting or modifying the final object here.
    }
